### ISSUE TITLE
Where should pull requests go? The Readme points to an older version of the book.

### ISSUE THREAD

**Issue by mr-threepwood** [rust-embedded/discovery-mb2#2]
Hi everyone!

First of all, many thanks for this great book and all the effort that went into it. I am currently working through the course as I noted a few references to files in the repo that seem to have been renamed/moved and I would like to provide the corresponding updates to these references via pull requests.

However, the Readme of this repo points for issues as well as for pull requests to another [repo](https://github.com/rust-embedded/discovery) which introduced as the deprecated version of this book and leaves me somewhat confused about whether this is intentional or other references that might need an update. :sweat_smile:

If you could help me clarifying which is the correct spot for contributions to the current version of the book, I would be happy to provide those.

**Comment by BartMassey** [comment]
Fixed the broken links in the README. Thanks much for pointing this out.
