### ISSUE TITLE
Stuck on 5.3 Debug it - `continue` hangs

### ISSUE THREAD

**Issue by zanebliss** [rust-embedded/discovery-mb2#7]
I came here after seeing [this issue](https://github.com/rust-embedded/discovery/issues/564) in the Discovery repository.

I'm followed the step and installation steps in this repository, and I'm running into issues with the `gbd` debugger hanging on the example in 5.3 when running the `continue` command.

```
(gdb) target remote :1337
Remote debugging using :1337
0x00000172 in init::__cortex_m_rt_main () at mdbook/src/05-meet-your-software/examples/init.rs:19
19              wfi();
(gdb) break main
Breakpoint 1 at 0x15c: file mdbook/src/05-meet-your-software/examples/init.rs, line 10.
Note: automatically using hardware breakpoints for read-only addresses.
(gdb) continue
Continuing.

```

`next` produces a SIGINT.

```
(gdb) next

Program received signal SIGINT, Interrupt.
0x00000172 in init::__cortex_m_rt_main () at mdbook/src/05-meet-your-software/examples/init.rs:19
19              wfi();
```

**Comment by BartMassey** [comment]
There's been a lot of these kinds of things lately. I suspect we have a bug in our instructions somewhere. That said, these are hard for us to reproduce. What platform are you on. What `gdb` are you using and how did you install it? Did you compile for debug? Any information appreciated as we try to work this out.

**Comment by zanebliss** [comment]
Thanks for the response. 

I'm on Pop!_OS 22.04 LTS, with an 11th Gen Intel i7-1185G7 CPU, Intel TigerLake-LP GT2 graphics.

For `gbd`, `--version` outputs `GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1`. I installed it with this command, from this [source](https://docs.rust-embedded.org/discovery-mb2/03-setup/linux.html#ubuntu-2004-or-newer--debian-10-or-newer): `sudo apt install gdb-multiarch minicom libunwind-dev`.

After reviewing this again, I reran the commands under the [udev rules](https://docs.rust-embedded.org/discovery-mb2/03-setup/linux.html#udev-rules) section, specifically `sudo udevadm control --reload`. A yellow LED on my micro:bit 2 turned on, which wasn't on before. I had glossed over this section in discovery-mb2 because I had already done it in discovery and assumed it wasn't any different. After that, the `continue` command worked correctly.

I should have been more thorough. Since I'm no longer stuck, I'm going to close this.

**Comment by BartMassey** [comment]
Thanks for letting us know! Glad you got it working.

If you spot any differences between the instructions in discovery-mb2 and those in discovery, it would be good to hear of them; I too thought that part stayed pretty much the same.

**Comment by davelongdev** [comment]
I'm having a similar issue at the moment.  I'm on arch linux.  I run cargo embed --example init, which seems to work.  Then I'm getting this, instead of what's indicated in the book.

```
% gdb-arm ../../../target/thumbv7em-none-eabihf/debug/examples/init
...
Reading symbols from ../../../target/thumbv7em-none-eabihf/debug/examples/init...
(gdb) target remote :1337
Remote debugging using :1337
cortex_m::asm::wfi ()
    at /home/dave/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cortex-m-0.7.7/src/asm.rs:56
56      }
(gdb) b main
Breakpoint 1 at 0x15c: file mdbook/src/05-meet-your-software/examples/init.rs, line 10.
Note: automatically using hardware breakpoints for read-only addresses.
(gdb) c
Continuing.
^C
Program received signal SIGINT, Interrupt.
cortex_m::asm::wfi ()
    at /home/dave/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/cortex-m-0.7.7/src/asm.rs:56
56      }
(gdb) quit
A debugging session is active.

        Inferior 1 [process 1] will be detached.

Quit anyway? (y or n) y
Detaching from program: /home/dave/rust-discovery-mb2/target/thumbv7em-none-eabihf/debug/examples/init, process 1
Ending remote debugging.
[Inferior 1 (process 1) detached]
```
